---
openapi: 3.0.1
info:
  title: API V1
  version: '1.0.0'
security:
  - bearerAuth: []
paths:
  "/api/v1/canvas":
    get:
      summary: list canvas
      responses:
        '200':
          description: successful
    post:
      summary: create canvas
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                chapter_id:
                  type: integer
                images:
                  type: array
                  items:
                    type: string
                    format: binary
              required:
                - chapter_id
                - images
      responses:
        '200':
          description: successful
  "/api/v1/canvas/{id}/remove_like":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete like
      responses:
        '200':
          description: successful
  "/api/v1/canvas/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show canva
      responses:
        '200':
          description: successful
  "/api/v1/storiettes":
    get:
      summary: list storiettes
      responses:
        '200':
          description: successful
  "/api/v1/storiettes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show storiette
      responses:
        '200':
          description: successful
  "/api/v1/likes":
    get:
      summary: list likes
      responses:
        '200':
          description: successful
    post:
      summary: create like
      requestBody:
        $ref: '#/components/requestBodies/likeBody'
      responses:
        '200':
          description: successful
  "/api/v1/likes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show like
      responses:
        '200':
          description: successful
  "/api/v1/opinions":
    get:
      summary: list opinions
      responses:
        '200':
          description: successful
    post:
      summary: create opinion
      requestBody:
        $ref: '#/components/requestBodies/opinionBody'
      responses:
        '200':
          description: successful
  "/api/v1/opinions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show opinion
      responses:
        '200':
          description: successful
  "/api/v1/chapters":
    get:
      summary: list chapters
      responses:
        '200':
          description: successful
    post:
      summary: create chapter
      requestBody:
        $ref: '#/components/requestBodies/chapterBody'
      responses:
        '200':
          description: successful
  "/api/v1/chapters/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show chapter
      responses:
        '200':
          description: successful
  "/api/v1/chapters/{id}/check_queue":
    parameters:
    - name: id
      in: path
      description: chapter id
      required: true
      schema:
        type: integer
    get:
      summary: check if user can create canvas on chapter
      responses:
        '200':
          description: successful
  "/api/v1/chapters/{id}/user_position_in_queue":
    parameters:
    - name: id
      in: path
      description: chapter id
      required: true
      schema:
        type: integer
    get:
      summary: check for the user position on the chapter queue
      responses:
        '200':
          description: successful
  "/api/v1/chapters/{id}/remove_user_from_queue":
    parameters:
    - name: id
      in: path
      description: chapter id
      required: true
      schema:
        type: integer
    get:
      summary: remove user from queue instantly
      responses:
        '200':
          description: successful
  "/api/v1/chapters/{id}/last_three_canvas":
    parameters:
    - name: id
      in: path
      description: chapter id
      required: true
      schema:
        type: integer
    get:
      summary: get last 3 canvas created on a chapter
      responses:
        '200':
          description: successful
  "/api/v1/chapters/{id}/add_user_to_queue":
    parameters:
    - name: id
      in: path
      description: chapter id
      required: true
      schema:
        type: integer
    get:
      summary: get last 3 canvas created on a chapter
      responses:
        '200':
          description: successful
  "/api/v1/graphic_resources":
    get:
      summary: list graphic_resources
      responses:
        '200':
          description: successful
  "/api/v1/graphic_resources/resource_for_type?resource_type={resource_type}":
    parameters:
    - name: resource_type
      in: path
      description: resource_type
      required: true
      schema:
        type: string
        enum: [character, dialog, object, background]
    get:
      summary: list graphic_resource by type
      responses:
        '200':
          description: successful
  "/api/v1/graphic_resources/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show graphic_resource
      responses:
        '200':
          description: successful
  "/api/v1/characters":
    get:
      summary: list characters
      responses:
        '200':
          description: successful
  "/api/v1/characters/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show character
      responses:
        '200':
          description: successful
    patch:
      summary: update character
      requestBody:
        $ref: '#/components/requestBodies/characterBody'
      responses:
        '200':
          description: successful
    put:
      summary: update character
      requestBody:
        $ref: '#/components/requestBodies/characterBody'
      responses:
        '200':
          description: successful
    delete:
      summary: delete character
      responses:
        '200':
          description: successful
  "/api/v1/descriptions":
    get:
      summary: list descriptions
      responses:
        '200':
          description: successful
  "/api/v1/descriptions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show description
      responses:
        '200':
          description: successful
  "/api/v1/conventions":
    get:
      summary: list conventions
      responses:
        '200':
          description: successful
  "/api/v1/conventions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show convention
      responses:
        '200':
          description: successful
  "/api/v1/user_profiles":
    post:
      summary: create user profile
      responses:
        '200':
          description: successful
          examples:
            Nacho:
              value:
                id: 1
                name: Nacho Smith
                given_name: Nacho
                family_name: Smith
                email: nacho_smith@gmail.com
                picture: nil
                wallet_address: nil
                sub: google-oauth2|1234949099349
                created_at: "2024-01-01"
                updated_at: "2024-01-01"
  "/api/v1/user_profiles/update_profile":
    patch:
      summary: update user profile
      requestBody:
        $ref: '#/components/requestBodies/userProfileBody'
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'   # Reference to an object
              examples:
                Nacho:
                  value:
                    id: 1
                    name: Nacho Smith
                    given_name: Nacho
                    family_name: Smith
                    email: nacho_smith@gmail.com
                    picture: nil
                    wallet_address: nil
                    sub: google-oauth2|1234949099349
                    created_at: "2024-01-01"
                    updated_at: "2024-01-01"
  "/api/v1/user_profiles/canvas":
    get:
      summary: get user profile canvas
      responses:
        '200':
          description: successful
  "/api/v1/user_profiles/info":
    get:
      summary: get user profile information
      responses:
        '200':
          description: successful
  "/api/v1/terms_and_conditions":
    get:
      summary: list terms_and_conditions
      responses:
        '200':
          description: successful
  "/api/v1/terms_and_conditions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show terms_and_condition
      responses:
        '200':
          description: successful
  "/api/v1/logos":
    get:
      summary: list logos
      responses:
        '200':
          description: successful
  "/api/v1/logos/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show logo
      responses:
        '200':
          description: successful
  "/api/v1/nft_transfers":
    post:
      summary: create nft transfers
      requestBody:
        $ref: '#/components/requestBodies/nftTransferBody'
      responses:
        '200':
          description: successful
  "/api/v1/queue_times/remove_user_time":
    get:
      summary: show queue time for removing user from queue once creating canva
      responses:
        '200':
          description: successful
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Canva:
      type: object
      required:
        - image
        - chapter_id
      optional:
        - title
        - active
      properties:
        image:
          type: string
          format: base64
        chapter_id:
          type: integer
        title:
          type: string
        active:
          type: boolean
    Storiette:
      type: object
      required:
        - image
        - title
      optiona:
        - description
        - active
    Chapter:
      type: object
      required:
        - title
        - storiette_id
      optional:
        - description
        - active
    GraphicResource:
      type: object
      required:
        - image
        - resource_type
      properties:
        resource_type:
          type: integer
          enum: [dialog, object, background]
        image:
          type: string
          format: base64
    Character:
      type: object
      required:
        - images
        - name
      optional:
        - active
        - description_ids
      properties:
        name:
          type: string
        images:
          type: string
          format: base64
        description_ids:
          type: array
        active:
          type: boolean
    Convention:
      type: object
      required:
        - name
        - image
      optional:
        - active
        - description_ids
      properties:
        name:
          type: string
        image:
          type: string
          format: base64
        active:
          type: boolean
        description_ids:
          type: array
    Description:
      type: object
      required:
        - title
        - text
        - descriptionable_type
        - descriptionable_id
      optional:
        - active
    Opinion:
      type: object
      required:
        - text
        - canva_id
      optional:
        - active
    Like:
      type: object
      required:
        - canva_id
    UserProfile:
      type: object
      required:
        - given_name
        - family_name
        - email
        - image
      optional:
        - wallet_address
        - picture
      properties:
        given_name:
          type: string
        family_name:
          type: string
        image:
          type: string
          format: base64
        email:
          type: string
        picture:
          type: string
        wallet_address:
          type: string
    TermsAndCondition:
      type: object
      required:
        - file
      optional:
        - active
      properties:
        file:
          type: string
          format: base64
        active:
          type: boolean
    Logo:
      type: object
      required:
        - image
      optional:
        - active
      properties:
        image:
          type: string
          format: base64
        active:
          type: boolean
    NftTransfer:
      type: object
      required:
        - from_address
        - to_address
        - transaction_hash
      properties:
        from_address:
          type: string
        to_address:
          type: string
        transaction_hash:
          type: string
  requestBodies:
    storietteBody:
      description: A JSON object containing storiette information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Storiette'
          example:
            storiette:
              title: Storiette number 1#
              description: "Storiette number 1"
              active: true
    chapterBody:
      description: A JSON object containing chapter information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Chapter'
          example:
            chapter:
              title: Chapter number 1#
              description: "Chapter number 1"
              storiette_id: 1
              active: true
    canvaBody:
      description: A JSON object containing canva information
      required: true
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/Canva'
    graphicResourceBody:
      description: A JSON object containing graphic resource information
      required: true
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/GraphicResource'
    characterBody:
      description: A JSON object containing character information
      required: true
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/Character'
    likeBody:
      description: A JSON object containing like information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Like'
          example:
            canva_id: '1'
    opinionBody:
      description: A JSON object containing opinion information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Opinion'
          example:
            canva_id: '1'
            text: 'some text'
            active: true
    termsAndConditionBody:
      description: A JSON object containing terms and condition information
      required: true
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/TermsAndCondition'
    logoBody:
      description: A JSON object containing logo information
      required: true
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/Logo'
    descriptionBody:
      description: A JSON object containing description information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Description'
          example:
            description:
              title: 'Description title'
              text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
              descriptionable_type: 'Character'
              descriptionable_id: 1
              active: true
    conventionBody:
      description: A JSON object containing convention information
      required: true
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/Convention'
    userProfileBody:
      description: A JSON object containing user profile information
      required: true
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/UserProfile'
    nftTransferBody:
      description: A JSON object containing nft transfer information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NftTransfer'
          example:
            nft_transfer:
              from_address: "from address"
              to_address: "to address"
              transaction_hash: "transaction hash"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
